  𝄆  [About me](https://samusz.github.io/about/aboutme)  𝄄  [_tools setup_](https://samusz.github.io/about/tools) 𝄇
--- 
Here I will detail some of my ideas and experience with the process of writting on a computer. 

# Preambule 

Writting on a computer isn't a easy task. 
You have to learn many different tricks and adapt your practice to external constraints all the time. 
Foremost the choice of OS isn't yours. The choice of document file isn't yours. The choice of workflow isn't yours. 

Usually it comes down to what the team uses as an OS and if Windo$, the word, if macO$ then word and (so rarely) if unixe then LaTeX ! 


# Editors 



---

  𝄆  [About me](https://samusz.github.io/about/aboutme)  𝄄  [_tools setup_](https://samusz.github.io/about/tools) 𝄇
